### ISSUE TITLE
Durability fails to deserialize rules containing conditions with an empty constraint

### ISSUE THREAD

**Issue by EthanEChristian** [cerner/clara-rules#352] opened 2017-10-22 04:53 UTC
Given a rule similar to:
```
(defrule some-rule
  [SomeFact ()]
  =>
  (insert! (->AnotherFact))
```
When deserializing this rule we see an error:
`"No matching ctor found for class java.util.Arrays$ArrayList"`
Thrown by try-eval, when called [here](https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/durability.clj#L62).

This seems to be due to a missing Fressian Handler for the EmptyList class. Though something to note as well is that we probably don't need create an extra `if` when compiling constraints for a [condition](https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/compiler.clj#L292)

**Comment by WilliamParker** [comment] 2017-10-25 00:18
After some investigation, it seems that when EmptyList is serialized and deserialized again, the result is a java.util.Arrays$ArrayList.  Print-dup expects that any collection has a constructor which takes a collection, and [constructs a form like](https://github.com/clojure/clojure/blob/clojure-1.8.0/src/clj/clojure/core_print.clj#L166)

````
(java.util.Arrays$ArrayList. [original-contents])
````

Print-dup is needed here to convert user string forms into compilable forms.  This doesn't work in this case since the private collection class in question has no such constructor, as can be seen from its [OpenJDK source](https://github.com/openjdk-mirror/jdk7u-jdk/blob/jdk7u6-b08/src/share/classes/java/util/Arrays.java#L2834).

Even with no handler, java.utils.Arrays$ArrayList is printed by Fressian somewhow, perhaps by a default implementation of some kind. I haven't yet tracked down why Fressian's behavior is the way it is.

**Comment by mrrodriguez** [comment] 2017-10-25 00:31
@WilliamParker in the main Fressian core there are default “core” handlers defined. The one in this case that is activated is probably the java.util.List. 

I don’t have all details on hand but around https://github.com/Datomic/fressian/blob/master/src/org/fressian/impl/Handlers.java#L321 

We don’t want things like this slipping through to defaults like that though. I’m not sure how that relates to `print-dup` though. This is Fressian SerDe which I didn’t think relates?

**Comment by mrrodriguez** [comment] 2017-10-25 16:16
@WilliamParker 

Ok, I took a closer look and have a better understanding of this issue now. It is only about Fressian having an issue with the empty list. Which speaks to your point (1) above.

From the PR, Ethan edited one rule `clara.durability-rules/find-wind-speeds-without-temp` to demonstrate the problem.

```clj
(defrule find-wind-speeds-without-temp
  "Rule using NegationNode"
  [?w <- WindSpeed
   ;; Empty constraint to test the serializing EmptyList, see Issue 352 for more information
   ()
   (= ?loc location)]
  [:not [Temperature (= ?loc location)]]
  =>
(insert! (->UnpairedWindSpeed ?w)))
```

This compiles to (ignoring irrelevant parts).
```clj

{:ns-name clara.durability-rules,
 :lhs [{:type clara.rules.testfacts.WindSpeed, :constraints [() (= ?loc location)], :fact-binding :?w}
        <etc>],
 :rhs <etc>}
```

The condition `:constraints` were compiled into the `meta` `:alpha-expr` that is serialized via Fressian.

When reading this serialized `:apha-expr` content, the Fressian exception is from this sort of form (ignoring irrelevant parts):
```clj

{:constraints [() <etc>]}
```

Since the empty list was serialized and didn't have a way to be deserialized.

How it is serialized can be seen via:

```clj

(in-ns 'clara.test-fressian)


(def res
  ;; NOTE: `form` has empty list
  (let [form '{:constraints [()]}]

    (with-open [os (java.io.ByteArrayOutputStream.)
                ^FressianWriter wtr (fres/create-writer os :handlers df/write-handler-lookup)]
      ;; Write
      (fres/write-object wtr form)

      ;; Read
      (let [data (.toByteArray os)]
        (with-open [is (java.io.ByteArrayInputStream. data)
                    ^FressianReader rdr (fres/create-reader is :handlers df/read-handler-lookup)]

          (fres/read-object rdr))))))

res
;;= {:constraints [[]]}

```

The `[]` in the print from `res` above is misleading though, since the data type is not an `clojure.lang.IPersistentVector`
```clj

(map type (:constraints res))
;;= (java.util.Arrays$ArrayList)
```
This is because Fressian wrote it and read it as this via a default/core handler.


The specific error from this issue comes from `clara.rules.durability/add-alpha-fn` when it is trying to do `clara.rules.compiler/try-eval` on this resulting form.
Using `res` from mthe example above:

```clj
(require '[clara.rules.compiler :as com])

(com/try-eval res)

IllegalArgumentException No matching ctor found for class java.util.Arrays$ArrayList  clojure.lang.Reflector.invokeConstructor (Reflector.java:163)

```

This is the origin of the original error is below [1].

Clojure's `eval` doesn't treat any arbitrary data structure as code. It has to be specific data structures that are used within Clojure to represent code. For collections, this tends to be the peristent collections of `clojure.lang.*`.

So what is happening is that we end up trying to `eval` "native" Java collections types here. Clojure's `eval` makes assumptions within the `clojure.lang.LispReader` about how to read things, and this internal `java.util.Arrays$ArrayList` class doesn't meet those requirements.

It is subtle in the Clojure Compiler where it may or may not fail due to embedded objects like this. I won't point out all lines relevant to that, since it is a deep dive and most of it can vary from version to version (just impl deatils really at this point).




[1] More of the stacktrace is:


```clj
#error {
 :cause "No matching ctor found for class java.util.Arrays$ArrayList"
 :via
 [{:type java.lang.ExceptionInInitializerError
   :message nil
   :at [sun.reflect.NativeConstructorAccessorImpl newInstance0 "NativeConstructorAccessorImpl.java" -2]}
  {:type java.lang.IllegalArgumentException
   :message "No matching ctor found for class java.util.Arrays$ArrayList"
   :at [clojure.lang.Reflector invokeConstructor "Reflector.java" 163]}]
 :trace
 [[clojure.lang.Reflector invokeConstructor "Reflector.java" 163]
  [clojure.lang.LispReader$EvalReader invoke "LispReader.java" 1120]
  [clojure.lang.LispReader$DispatchReader invoke "LispReader.java" 691]
  [clojure.lang.LispReader read "LispReader.java" 263]
  [clojure.lang.LispReader read "LispReader.java" 196]
  [clojure.lang.LispReader read "LispReader.java" 185]
  [clojure.lang.RT readString "RT.java" 1821]
  [clojure.lang.RT readString "RT.java" 1816]
  [clara.test_fressian$eval19262 <clinit> "form-init4092453123691355234.clj" 51]
  [sun.reflect.NativeConstructorAccessorImpl newInstance0 "NativeConstructorAccessorImpl.java" -2]
  [sun.reflect.NativeConstructorAccessorImpl newInstance "NativeConstructorAccessorImpl.java" 62]
  [sun.reflect.DelegatingConstructorAccessorImpl newInstance "DelegatingConstructorAccessorImpl.java" 45]
  [java.lang.reflect.Constructor newInstance "Constructor.java" 423]
  [java.lang.Class newInstance "Class.java" 442]
  [clojure.lang.Compiler$ObjExpr eval "Compiler.java" 4843]
  [clojure.lang.Compiler eval "Compiler.java" 6781]
  [clojure.lang.Compiler eval "Compiler.java" 6745]
  [clojure.core$eval invoke "core.clj" 3081]
  [clara.rules.compiler$try_eval invoke "compiler.clj" 221]
  [clara.test_fressian$eval19260 invoke "form-init4092453123691355234.clj" 51]
  [clojure.lang.Compiler eval "Compiler.java" 6782]
  [clojure.lang.Compiler eval "Compiler.java" 6745]
  [clojure.core$eval invoke "core.clj" 3081]
  [clojure.main$repl$read_eval_print__7099$fn__7102 invoke "main.clj" 240]
  [clojure.main$repl$read_eval_print__7099 invoke "main.clj" 240]
  [clojure.main$repl$fn__7108 invoke "main.clj" 258]
  [clojure.main$repl doInvoke "main.clj" 258]
  [clojure.lang.RestFn invoke "RestFn.java" 1523]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__636 invoke "interruptible_eval.clj" 87]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invoke "core.clj" 630]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1868]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 85]
  [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__681$fn__684 invoke "interruptible_eval.clj" 222]
  [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__676 invoke "interruptible_eval.clj" 190]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}

```

**Comment by mrrodriguez** [comment] 2017-10-25 16:17
@WilliamParker 

As a separate comment, I think point (2) is slightly unrelated. The writing step is only being done here by Fressian. The issue is on reading and what Clojure is capable of `eval`ing.

**Comment by WilliamParker** [comment] 2017-10-26 15:56
@mrrodriguez I think we're on the same page here.  In any case, my reason for investigating the cause of the specific exception being thrown was to ensure that the proposed fix in https://github.com/cerner/clara-rules/pull/353 of adding a Fressian handler for EmptyList would work and that there wasn't some other factor at work that I was unaware of.  I'm satisfied on that point now.

**Comment by WilliamParker** [comment] 2017-10-27 20:18
I've merged https://github.com/cerner/clara-rules/pull/353.  Is there anything else anyone wanted to address before closing this issue?

**Comment by mrrodriguez** [comment] 2017-10-30 00:03
Nothing from me.

**Comment by WilliamParker** [comment] 2017-10-30 14:17
Closing.

**Closed by WilliamParker** 2017-10-30 14:17 UTC
Labels: bug, durability
