### ISSUE TITLE
Working memory Exception for 25% of events upon processing batch of events.

### ISSUE THREAD

**Issue by vinamrajain** [cerner/clara-rules#465] opened 2021-02-18 20:13 UTC
I have integrated the Clara rule engine with my spring application to evaluate bunch of rules. When processing one event at a time, it seems to be working fine but upon sending a batch of 4+ events, 25% of the events throw Exception : Exception in accessing working memory. What's weird is the the cap of 25% (strict 25%) all the time which batched varying from 4 to 200 events. i.e. 1 out of 4 event throws the exception.

Did someone else faced this issue during performance testing? Any helps is highly appreciated.

**Comment by EthanEChristian** [comment] 2021-02-18 20:57
@vinamrajain,
Im not sure if I have ever encounter such an error before. An error specifically to batching of fact seems peculiar to me.

Can you provide a stacktrace(removing anything sensitive)?

**Comment by vinamrajain** [comment] 2021-02-18 21:27
@EthanEChristian - Thanks for the reply. Please find the stack trace below. 

[ERROR] [] [boundedElastic-14] -  - Exception occurred while executing the rules: message = Exception in accessing working memory
[CustomException]: Exception in accessing working memory
Service.executeRules(Service.java:94)	
at EventProcessor.processEvent(EventProcessor.java:51)
at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:502)
at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:217)
at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:250)
at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$1(PartitionPumpManager.java:182)
at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:439)
at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: No namespace: xyz.abc.rules found
at clojure.core$the_ns.invokeStatic(core.clj:4128)
at clojure.core$ns_interns.invokeStatic(core.clj:4173)
at clojure.core$ns_interns.invoke(core.clj:4173)
at clara.rules$eval7562$fn__7563.invoke(rules.cljc:294)
at clara.rules.compiler$eval6003$fn__6004$G__5994__6009.invoke(compiler.clj:39)
at clara.rules.compiler$mk_session$fn__7375.invoke(compiler.clj:2048)
at clojure.core$map$fn__5587.invoke(core.clj:2747)
at clojure.lang.LazySeq.sval(LazySeq.java:40)
at clojure.lang.LazySeq.seq(LazySeq.java:49)
at clojure.lang.RT.seq(RT.java:528)
at clojure.core$seq__5124.invokeStatic(core.clj:137)
at clojure.core$apply.invokeStatic(core.clj:652)
at clojure.core$mapcat.invokeStatic(core.clj:2775)
at clojure.core$mapcat.doInvoke(core.clj:2775)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at clara.rules.compiler$mk_session.invokeStatic(compiler.clj:2047)
at clara.rules.compiler$mk_session.invoke(compiler.clj:2039)
at clara.rules.java$mk_java_session.invokeStatic(java.clj:52)
at clara.rules.java$mk_java_session.invoke(java.clj:50)
at clojure.lang.Var.invoke(Var.java:381)
at clara.rules.RuleLoader.loadRules(RuleLoader.java:44)
at DeterministicEngineFactory.getClaraReteEngine(DeterministicEngineFactory.java:23)
at EmptyWorkingMemoryFactory.create(EmptyWorkingMemoryFactory.java:16)
at EmptyWorkingMemoryFactory.create(EmptyWorkingMemoryFactory.java:12)
at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:58)
at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
at Service.executeRules(Service.java:82)
... 17 common frames omitted

**Comment by EthanEChristian** [comment] 2021-02-19 21:12
@vinamrajain,
Thats an odd one, looking at the code the exception seems to stem from [here](https://github.com/cerner/clara-rules/blob/e96dbc6cff1ea47418c7b92340a2038d530e32d6/src/main/clojure/clara/rules.cljc#L294). However, based on the call stack i would have expected this sort of namespace error to have occurred higher in the stack, specifically in the [requiring](https://github.com/cerner/clara-rules/blob/8107a5ab7fdb475e323c0bcb39084a83454deb1c/src/main/java/clara/rules/RuleLoader.java#L40-L41) of the namespace/s.

Is this being called in parallel?

**Comment by vinamrajain** [comment] 2021-02-20 16:56
@EthanEChristian 

Yes parallel calls.

**Comment by WilliamParker** [comment] 2021-02-25 09:20
Just to check, but the the arguments to [loadRules](https://github.com/cerner/clara-rules/blob/8107a5ab7fdb475e323c0bcb39084a83454deb1c/src/main/java/clara/rules/RuleLoader.java#L37) are all namespaces correct?

From your last comment about parallel calls I suspect that might be the issue - Clara ultimately invokes Clojure's runtime compilation via eval, which is not thread-safe.  Note that it is fine to use sessions in different threads once created, it is just the creation that is a problem in terms of thread safety.  Perhaps we should place a lock around session creation to enforce that only one thread can do it at a time.  

Could you try your use-case with a single thread and see if that resolves the issue?  If it doesn't some kind of example replicating the issue would be helpful.

**Comment by EthanEChristian** [comment] 2021-02-25 14:52
@WilliamParker,

Thats what i was thinking as well, though I haven't found time yet to replicate the issue. 
My first thought was that we would simply wrap the loader's [require](https://github.com/cerner/clara-rules/blob/8107a5ab7fdb475e323c0bcb39084a83454deb1c/src/main/java/clara/rules/RuleLoader.java#L40-L41) in a `synchronized` block.

**Comment by WilliamParker** [comment] 2021-03-01 01:37
Frankly I think replicating the issue is likely to be extremely challenging if not impossible.  And even if we could, I'm not sure it matters - ultimately we know that the require here is not thread-safe, so we shouldn't be doing it this way anyway even if it happened to work out at the moment for whatever reason.

The remaining question IMO is whether we should synchronize at the level of that require or somewhere in compiler.clj - I can't think of a reason offhand why the kind of eval calls we make there wouldn't be thread safe but I'm not entirely convinced they are.

**Comment by WilliamParker** [comment] 2021-03-01 01:39
@vinamrajain in the meantime you might try wrapping your call to loadRules in a synchronized block and seeing if that resolves your issue.

**Comment by mrrodriguez** [comment] 2021-03-01 17:53
> Frankly I think replicating the issue is likely to be extremely challenging if not impossible. And even if we could, I'm not sure it matters - ultimately we know that the require here is not thread-safe, so we shouldn't be doing it this way anyway even if it happened to work out at the moment for whatever reason.
> 
> The remaining question IMO is whether we should synchronize at the level of that require or somewhere in compiler.clj - I can't think of a reason offhand why the kind of eval calls we make there wouldn't be thread safe but I'm not entirely convinced they are.

@WilliamParker I'm not sure you can simply wrap `require` in a syncronized block or not.
Notably, `requiring-resolve` was added in 1.10 to clj to deal with this issue and maybe will make it's way as the default eventually.
See:
* https://ask.clojure.org/index.php/9893/require-is-not-thread-safe

Locking at some level of granularity around the entire `mk-session` maybe good enough though. I'm just not sure.

**Comment by vinamrajain** [comment] 2021-03-01 18:42
@WilliamParker @EthanEChristian @mrrodriguez 

Thank you for all the comments above. We were creating an object pool of Working Memory, and those objects were borrowed and released each time the set of rules are executed. The borrow method was not thread safe and hence the exception of accessing working memory. Now we have instantiated a final static working memory object explicitly instead of borrowing from object pool.
The initial working memory created by loading rules is expected to be immutable. Any time facts are loaded or rules are fired, a new working memory is created. Hence a single copy of immutable working memory should be sufficient from which other working memories are created.

 This resolved the issue.

**Comment by EthanEChristian** [comment] 2021-06-29 16:18
Im going to close this issue, vinamrajain has provided a path forward to avoid the race condition in his answer above.

We can re-open the issue if we encounter the need to in the future.

**Closed by EthanEChristian** 2021-06-29 16:18 UTC
